<?php
  $this->headTitle('Імпорт');
  $this->mainMenu()->setActiveItemId('import');
?>
<div class="jumbotron">
    <h1><span class="zf-green">Імпорт</span></h1>

    <div class="input-group">
    <label class="form-control" for="param">Виберіть тип</label>
    <select class="form-control" size="auto" id="param">
      <option selected value="collection_listings">Колекції</option>
      <option value="products">Товари</option>
      <option value="collects">Товари в колекції</option>
    </select>
      <a class="btn btn-success btn-lg" href="javascript:void(0);" onclick="return clickMe(this)">Import</a>
  </div>
</div>

<div class="row">

</div>
